server:
  port: 8282
spring:
  application:
    name: device-service
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: chowder
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true  
  zipkin:
    base-url: http://localhost:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8888/uaa/token_keys
  
eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

feign:
  circuitbreaker:
    enabled: false

logging:
  level:
    root: INFO
    com.scg.service: TRACE
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    
logging.level.*: info  